name: Sync Images to Cloudflare R2

on:
  push:
    branches:
      - main
      - master
    paths:
      - '**/*.png'
      - '**/*.PNG'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.webp'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync to Cloudflare R2
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.R2_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://${{ secrets.R2_ACCOUNT_ID }}.r2.cloudflarestorage.com
          SOURCE_DIR: ''
          DEST_DIR: ''
